### ISSUE TITLE
Enable button doesn't toggle off

### ISSUE THREAD

**Issue by jakequi** [s0t7x/decky-sunshine#52]
I've managed to manually install the newest Nightly under releases, and I have it working fine. However, after I enable Sunshine, I can't disable it again. When I press the toggle, it just loads and stays on. The log says something along the lines of "Stopping sunshine..." then carries on as normal

**Comment by causa-prima** [comment]
If you are talking about [nightly-20250326-073454](https://github.com/s0t7x/decky-sunshine/releases/tag/nightly-20250326-073454) : my apologies, that would most likely be my fault. I assumed that before my pull request #51 was merged, someone would actually test it. I did not, as at the point of writing it, I did not look into how to do that. I fixed these bugs in #55, so please check again after this has been merged a new (nightly) version is available.

**Comment by jakequi** [comment]
Resolved!

**Comment by avichou** [comment]
> The PR [#55](https://github.com/s0t7x/decky-sunshine/pull/55) was merged, so there's a [new nightly](https://github.com/s0t7x/decky-sunshine/releases/tag/nightly-20250402-064303) you can test.

not fixed for me. using the latest nightly from 2 weeks ago, the issue is still present. this is the first time i install sunshine btw

**Comment by causa-prima** [comment]
Closed because of missing feedback.
